#ifndef __Resource_H
#define __Resource_H

#define ID_ACCELERATORS 100

#define ID_MAINMENU     5
#define ID_POPUPMENU    6

#define ID_FILE_OPEN   10
#define ID_FILE_SAVE   11
#define ID_FILE_SAVEAS 12
#define ID_FILE_EXIT   15


#define ID_SDTS_VIEWTYPES 116
#define ID_SDTS_ADD       117

#define ID_SDTS_DLG       116

#define ID_SDTS_DLG_LISTBOX       200
#define ID_SDTS_DLG_TEXT          201
#define ID_SDTS_DLG_EDIT_EDIT     202
#define ID_SDTS_DLG_EDIT_ADD      203
#define ID_SDTS_DLG_BUTTON_OK     204
#define ID_SDTS_DLG_BUTTON_REMOVE 205
#define ID_SDTS_DLG_BUTTON_EDIT   206
#define ID_SDTS_DLG_BUTTON_ADD    207

#define ID_TILEPROPERTIES_DIALOG                   400
#define ID_TILEPROPERTIES_DIALOG_BUTTON_OK         401
#define ID_TILEPROPERTIES_DIALOG_BUTTON_CANCEL     402
#define ID_TILEPROPERTIES_DIALOG_TEXT_SOLIDITY     404
#define ID_TILEPROPERTIES_DIALOG_TRACKBAR_SOLIDITY 405
#define ID_TILEPROPERTIES_DIALOG_UPDOWN            406
#define ID_TILEPROPERTIES_DIALOG_EDIT_TILEID       407
#define ID_TILEPROPERTIES_DIALOG_TEXT_TILEID       408
#define ID_TILEPROPERTIES_DIALOG_STATIC            409
#define ID_TILEPROPERTIES_DIALOG_EDIT_SOLIDITY     410
#define ID_TILEPROPERTIES_DIALOG_TRACKBAR_TILEID   411
#define ID_TILEPROPERTIES_DIALOG_EDIT_TILEX        412
#define ID_TILEPROPERTIES_DIALOG_EDIT_TILEY        413
#define ID_TILEPROPERTIES_DIALOG_TEXT_X            414
#define ID_TILEPROPERTIES_DIALOG_TEXT_Y            415
#define ID_TILEPROPERTIES_DIALOG_BUTTON_REMOVE     416
#define ID_TILEPROPERTIES_DIALOG_BUTTON_ADD        417
#define ID_TILEPROPERTIES_DIALOG_LISTBOX           418
#define ID_TILEPROPERTIES_DIALOG_TEXT_DATA         419
#define ID_TILEPROPERTIES_DIALOG_EDIT_DATA         420

#endif

