#ifndef __Resource_H
#define __Resource_H

#define ID_MAINMENU                          2

#define ID_FILE_NEW          1
#define ID_FILE_RENAME       2
#define ID_FILE_OPEN_TILEMAP 3
#define ID_FILE_OPEN_TILE    4
#define ID_FILE_OPEN_IMAGE   5
#define ID_FILE_SAVE         6
#define ID_FILE_SAVEAS       7
#define ID_FILE_CLOSE        8
#define ID_FILE_CLOSEALL     9
#define ID_FILE_EXIT        10

#define ID_EDIT_SOLIDITY              11
#define ID_EDIT_DISELECT              12
#define ID_EDIT_SELECTTHISINDEX       13
#define ID_EDIT_RELOADTHISINDEX       14
#define ID_EDIT_COPY                  15
#define ID_EDIT_CUT                   16
#define ID_EDIT_PASTE                 17
#define ID_EDIT_UNDO                  18
#define ID_EDIT_REDO                  19
#define ID_EDIT_RESIZEMAP             20
#define ID_EDIT_PROPERTIES            21
#define ID_EDIT_SAVETHISINDEXAS       22
#define ID_EDIT_SPRITES_ADDSPRITE     23
#define ID_EDIT_SPRITES_DELETESPRITES 24
#define ID_EDIT_SPRITES_SPRITESTATS   25

#define ID_EDIT_SPRITES_SPECIALDATATYPES 40

#define ID_ASTAR_CREATESTART 26
#define ID_ASTAR_CREATEEND   27
#define ID_ASTAR_RUN         28
#define ID_ASTAR_SHOWSTATS   29

#define ID_OPTIONS_SCREENSHOT 30
#define ID_HELP_ABOUT         31
#define ID_HELP_CONTENTS      32

#define ID_ACCELERATORS                     10

#define ID_NEWMAP_DIALOG                   100
#define ID_NEWMAP_DIALOG_BUTTON_CANCEL     101
#define ID_NEWMAP_DIALOG_BUTTON_OK         102
#define ID_NEWMAP_DIALOG_TEXT_WIDTH        103
#define ID_NEWMAP_DIALOG_TEXT_HEIGHT       104
#define ID_NEWMAP_DIALOG_EDIT_WIDTH        105
#define ID_NEWMAP_DIALOG_EDIT_HEIGHT       106
#define ID_NEWMAP_DIALOG_EDIT_TILESET      107
#define ID_NEWMAP_DIALOG_TEXT_TILESET      108
#define ID_NEWMAP_DIALOG_BUTTON_BROWSE     109
#define ID_NEWMAP_DIALOG_UPWOWN_WIDTH      110
#define ID_NEWMAP_DIALOG_UPWOWN_HEIGHT     111


#define ID_RESIZEMAP_DIALOG                200
#define ID_RESIZEMAP_DIALOG_BUTTON_CANCEL  201
#define ID_RESIZEMAP_DIALOG_BUTTON_OK      202
#define ID_RESIZEMAP_DIALOG_TEXT_WIDTH     203
#define ID_RESIZEMAP_DIALOG_TEXT_HEIGHT    204
#define ID_RESIZEMAP_DIALOG_EDIT_WIDTH     205
#define ID_RESIZEMAP_DIALOG_EDIT_HEIGHT    206
#define ID_RESIZEMAP_DIALOG_UPDOWN_WIDTH   207
#define ID_RESIZEMAP_DIALOG_UPDOWN_HEIGHT  208


#define ID_ABOUT_DIALOG                    300
#define ID_ABOUT_DIALOG_BUTTON_OK          301
#define ID_ABOUT_DIALOG_EDIT_VERSION       302
#define ID_ABOUT_DIALOG_TEXT_AUTHOR        303
#define ID_ABOUT_DIALOG_TEXT_AUTHOR_VALUE  304
#define ID_ABOUT_DIALOG_TEXT_CREDITS       305
#define ID_ABOUT_DIALOG_TEXT_CREDITS_VALUE 306
#define ID_ABOUT_DIALOG_TEXT_VERSION       307

#define ID_TILEPROPERTIES_DIALOG                   400
#define ID_TILEPROPERTIES_DIALOG_BUTTON_OK         401
#define ID_TILEPROPERTIES_DIALOG_BUTTON_CANCEL     402
#define ID_TILEPROPERTIES_DIALOG_TEXT_SOLIDITY     404
#define ID_TILEPROPERTIES_DIALOG_TRACKBAR_SOLIDITY 405
#define ID_TILEPROPERTIES_DIALOG_UPDOWN            406
#define ID_TILEPROPERTIES_DIALOG_EDIT_TILEID       407
#define ID_TILEPROPERTIES_DIALOG_TEXT_TILEID       408
#define ID_TILEPROPERTIES_DIALOG_STATIC            409
#define ID_TILEPROPERTIES_DIALOG_EDIT_SOLIDITY     410
#define ID_TILEPROPERTIES_DIALOG_TRACKBAR_TILEID   411
#define ID_TILEPROPERTIES_DIALOG_EDIT_TILEX        412
#define ID_TILEPROPERTIES_DIALOG_EDIT_TILEY        413
#define ID_TILEPROPERTIES_DIALOG_TEXT_X            414
#define ID_TILEPROPERTIES_DIALOG_TEXT_Y            415

#define ID_GETTILESFROMBITMAP_DIALOG               500
#define ID_GETTILESFROMBITMAP_VSCROLLBAR           501
#define ID_GETTILESFROMBITMAP_HSCROLLBAR           502
#define ID_GETTILESFROMBITMAP_STATIC               503
#define ID_GETTILESFROMBITMAP_BUTTON_OK            504
#define ID_GETTILESFROMBITMAP_BUTTON_CANCEL        505
#define ID_GETTILESFROMBITMAP_CHECK_GRID           506
#define ID_GETTILESFROMBITMAP_EDIT_PREFIX          507
#define ID_GETTILESFROMBITMAP_TEXT_PREFIX          508
#define ID_GETTILESFROMBITMAP_TEXT_INDEX           509
#define ID_GETTILESFROMBITMAP_EDIT_INDEX           510

#define ID_SOLIDITY_DIALOG                         603
#define ID_SOLIDITY_BUTTON_OK                      602
#define ID_SOLIDITY_TRACKBAR_SOLIDITY              603
#define ID_SOLIDITY_EDIT_SOLIDITY                  604
#define ID_SOLIDITY_BUTTON_CANCEL                  605
#define ID_SOLIDITY_TEXT_SOLIDITY                  606
#define ID_SOLIDITY_TEXT_TILEID                    607
#define ID_SOLIDITY_TEXT_X                         608
#define ID_SOLIDITY_TEXT_Y                         609
#define ID_SOLIDITY_EDIT_TILEID                    610
#define ID_SOLIDITY_EDIT_TILEX                     612
#define ID_SOLIDITY_EDIT_TILEY                     613
#define ID_SOLIDITY_TRACKBAR_TILEID                615
#define ID_SOLIDITY_STATIC                         616

#define ID_ASTARSTATS_DIALOG                       600
#define ID_ASTARSTATS_BUTTON_CANCEL                601
#define ID_ASTARSTATS_BUTTON_OK                    602
#define ID_ASTARSTATS_EDIT_TIMETAKEN               603
#define ID_ASTARSTATS_EDIT_TOTALNODESSEARCHED      604
#define ID_ASTARSTATS_EDIT_SHORTESTPATHLENGTH      605
#define ID_ASTARSTATS_TEXT_TIMETAKEN               606
#define ID_ASTARSTATS_TEXT_TOTALNODESSEARCHED      607
#define ID_ASTARSTATS_TEXT_SHORTESTPATHLENGTH      608
#define ID_ASTARSTATS_CHECK_ALLOWDIAGONAL          609
#define ID_ASTARSTATS_CHECK_SHOWNODES              610
#define ID_ASTARSTATS_CHECK_SHOWALLNODESSEARCHED   611
#define ID_ASTARSTATS_BUTTON_STARTSEARCH           612
#define ID_ASTARSTATS_TEXT_MAXPERCENTAGETOSEARCH   613
#define ID_ASTARSTATS_EDIT_MAXPERCENTAGETOSEARCH   614
#define ID_ASTARSTATS_UPDOWN_MAXPERCENTAGETOSEARCH 615
#define ID_ASTARSTATS_EDIT_NUMBEROFTILES           616
#define ID_ASTARSTATS_CHECK_SHOWSTARTANDENDNODES   617

#define ID_ADDSPRITE_DIALOG                        700
#define ID_ADDSPRITE_BUTTON_OK                     701
#define ID_ADDSPRITE_BUTTON_CANCEL                 702
#define ID_ADDSPRITE_BUTTON_BROWSE                 703
#define ID_ADDSPRITE_TEXT_DELAY                    704
#define ID_ADDSPRITE_TEXT_SPRITEINDEX              705
#define ID_ADDSPRITE_EDIT_SPRITEINDEX              706
#define ID_ADDSPRITE_EDIT_BROWSE                   707
#define ID_ADDSPRITE_EDIT_DELAY                    708
#define ID_ADDSPRITE_TEXT_CYCLELENGTH              709
#define ID_ADDSPRITE_EDIT_CYCLELENGTH              710
#define ID_ADDSPRITE_TAB                           711
#define ID_ADDSPRITE_STATIC                        712
#define ID_ADDSPRITE_UPDOWN_DELAY                  713
#define ID_ADDSPRITE_TEXT_X                        714
#define ID_ADDSPRITE_TEXT_Y                        715
#define ID_ADDSPRITE_EDIT_X                        716
#define ID_ADDSPRITE_EDIT_Y                        717
#define ID_ADDSPRITE_BUTTON_PLAY                   718
#define ID_ADDSPRITE_BUTTON_PAUSE                  719
#define ID_ADDSPRITE_BUTTON_STOP                   720
#define ID_ADDSPRITE_TRACKBAR_FRAME                721
#define ID_ADDSPRITE_CHECK_LOOP                    722
#define ID_ADDSPRITE_EDIT_FRAME                    723
#define ID_ADDSPRITE_TEXT_FRAME                    724
#define ID_ADDSPRITE_EDIT_ZOOM                     725
#define ID_ADDSPRITE_TEXT_ZOOM                     726
#define ID_ADDSPRITE_UPDOWN_ZOOM                   727
#define ID_ADDSPRITE_BUTTON_USETHISIMAGE           728
#define ID_ADDSPRITE_TEXT_AVAILABLEIMAGES          729
#define ID_ADDSPRITE_TRACKBAR_AVAILABLEIMAGES      730

#define ID_DELETESPRITE_DIALOG                       800
#define ID_DELETESPRITE_DIALOG_BUTTON_DELETE         801
#define ID_DELETESPRITE_DIALOG_BUTTON_CANCEL         802
#define ID_DELETESPRITE_DIALOG_TEXT_FRAME_INDEX      803
#define ID_DELETESPRITE_DIALOG_TEXT_SPRITE_INDEX     804
#define ID_DELETESPRITE_DIALOG_STATIC                805
#define ID_DELETESPRITE_DIALOG_TRACKBAR_SPRITE_INDEX 806
#define ID_DELETESPRITE_DIALOG_TRACKBAR_FRAME_INDEX  807
#define ID_DELETESPRITE_DIALOG_EDIT_FRAME_INDEX      803
#define ID_DELETESPRITE_DIALOG_EDIT_SPRITE_INDEX     804

#define ID_SPRITESTATS_DIALOG                        900
#define ID_SPRITESTATS_DIALOG_BUTTON_OK              901
#define ID_SPRITESTATS_DIALOG_BUTTON_CANCEL          902
#define ID_SPRITESTATS_DIALOG_STATIC                 903
#define ID_SPRITESTATS_DIALOG_TRACK_IMGID            904
#define ID_SPRITESTATS_DIALOG_TEXT_IMGID             905
#define ID_SPRITESTATS_DIALOG_EDIT_IMGID             906
#define ID_SPRITESTATS_DIALOG_BUTTON_REPLACEINDEX    907


#endif

